#' @title Execute the LINGUINE Pipeline
#'
#' @description Orchestrates the full Ancestral Genome Reconstruction Pipeline.
#' Parses the phylogenetic tree, processes extant tips, and iteratively traverses
#' internal nodes to reconstruct ancestral linkage groups.
#'
#' @param config A `linguine_config` object generated by `create_linguine_config()`.
#'
#' @return Invisible NULL. All processed data, HMM results, and visual plots are saved to the directories specified in the configuration object.
#' @export
run_linguine <- function(config) {

  message("=======================================================")
  message("          INITIALIZING LINGUINE PIPELINE               ")
  message("=======================================================")

  # 1. Setup Directories
  purrr::walk(config$paths, ~if (!dir.exists(.x)) dir.create(.x, recursive = TRUE))

  # 2. Parse Phylogenetic Tree
  message("\nReading and processing phylogenetic tree...")
  tree_path <- file.path(config$paths$raw_data, config$tree_filename)
  if (!file.exists(tree_path)) stop("CRITICAL ERROR: Tree file not found at: ", tree_path)

  speciesTree <- phytools::read.newick(tree_path)
  if(is.null(speciesTree$node.label)) speciesTree <- ape::reorder.phylo(speciesTree, order = "postorder")

  tips <- speciesTree$tip.label
  Ntips <- length(tips)
  internal_nodes <- (Ntips + 1):(Ntips + speciesTree$Nnode)
  internal_node_daughters <- list()

  message("Mapping internal nodes...")
  for (node_index in 1:length(internal_nodes)) {
    curr_node <- rev(internal_nodes)[node_index]
    child_rows <- which(speciesTree$edge[, 1] == curr_node)
    daughter_indices <- speciesTree$edge[child_rows, 2]
    daughter_labels <- sapply(daughter_indices, get_label, tree = speciesTree)

    node_name <- if(is.null(speciesTree$node.label)) paste0("INode_", curr_node) else rev(speciesTree$node.label)[node_index]
    internal_node_daughters[[node_name]] <- daughter_labels
    message(sprintf("  %s: %s vs %s", node_name, daughter_labels[1], daughter_labels[2]))
  }

  if(is.null(speciesTree$node.label)) speciesTree$node.label <- rev(names(internal_node_daughters))

  # ----------------------------------------------------------------------------
  # Tree Visualization
  # ----------------------------------------------------------------------------
  plot_filename <- file.path(config$paths$plots, "phylogenetic_tree_with_nodes.png")
  grDevices::png(filename = plot_filename, width = 1200, height = 800, res = 100)
  ape::plot.phylo(speciesTree, type = "phylogram", show.node.label = FALSE, main = "Species Tree with Internal Nodes")
  ape::nodelabels(text = speciesTree$node.label, node = internal_nodes, bg = "yellow", col = "black", cex = 1.0, frame = "rect")
  grDevices::dev.off()
  message("\nTree visualization saved to: ", plot_filename)

  # 3. Pre-process Extant Species
  message("\nPre-processing all extant species genomes...")
  for (tip_species in tips) {
    process_extant_genome(species_name = tip_species, is_inode = FALSE, config = config)
  }
  message("Pre-processing complete. Extant lineages validated.")

  # 4. Launch Reconstruction Loop
  for(cont in 1:length(internal_node_daughters)) {

    parent <- names(internal_node_daughters)[cont]
    d1 <- internal_node_daughters[[cont]][1]
    d2 <- internal_node_daughters[[cont]][2]

    is_d1_inode <- !(d1 %in% tips)
    is_d2_inode <- !(d2 %in% tips)

    # Sort for consistency
    if (is_d1_inode == is_d2_inode) {
      sorted <- sort(c(d1, d2)); ref_species <- sorted[1]; comp_species <- sorted[2]
    } else {
      if (!is_d1_inode) { ref_species <- d1; comp_species <- d2 } else { ref_species <- d2; comp_species <- d1 }
    }

    is_ref_inode <- !(ref_species %in% tips)
    is_comp_inode <- !(comp_species %in% tips)

    comparison_type <- if (!is_ref_inode & !is_comp_inode) "tip_vs_tip" else if (!is_ref_inode & is_comp_inode) "tip_vs_INode" else "INode_vs_INode"

    message(sprintf("\n======================================================="))
    message(sprintf("Processing Node: %s (%s vs %s) | Architecture: %s", parent, ref_species, comp_species, comparison_type))
    message(sprintf("======================================================="))

    # Execution Sequence
    hmm_obs <- prepare_synteny_data(ref_species, comp_species, comparison_type, parent, internal_node_daughters[[comp_species]], config)
    hmm_class <- run_synteny_hmm(ref_species, comp_species, comparison_type, hmm_obs, config)
    extract_synteny_architecture(ref_species, comp_species, comparison_type, hmm_class, config)
    plot_synteny_summary(ref_species, comp_species, comparison_type, config)

    # Reciprocal execution for tip_vs_tip
    if (comparison_type == "tip_vs_tip") {
      message("\n--- Executing Reciprocal Architecture (Comp vs Ref) ---")
      hmm_obs_recip <- prepare_synteny_data(comp_species, ref_species, comparison_type, parent, NULL, config)
      hmm_class_recip <- run_synteny_hmm(comp_species, ref_species, comparison_type, hmm_obs_recip, config)
      extract_synteny_architecture(comp_species, ref_species, comparison_type, hmm_class_recip, config)
    }

    reconstruct_node(ref_species, comp_species, comparison_type, parent, speciesTree, config)
    plot_architecture(ref_species, comp_species, comparison_type, parent, config)

    message(sprintf("\nProcessing completed successfully for Node: %s", parent))
  }

  message("\n=======================================================")
  message("         LINGUINE PIPELINE COMPLETE                    ")
  message("=======================================================")

  return(invisible(NULL))
}
