#' @title Execute Synteny HMM Inference
#'
#' @description Configures transition/emission matrices dynamically based on input
#' dimensions and applies the Viterbi algorithm to decode hidden ancestral states.
#'
#' @param ref_species Character. Reference lineage.
#' @param comp_species Character. Comparison lineage.
#' @param comparison_type Character. Architecture of the comparison.
#' @param hmm_obs_path Character. Path to the RDS file generated by prepare_synteny_data.
#' @param config A `linguine_config` object.
#'
#' @return Character path to the saved HMM classification RDS file.
#' @export
run_synteny_hmm <- function(ref_species, comp_species, comparison_type, hmm_obs_path, config) {

  if (comparison_type == "INode_vs_INode" || is.null(hmm_obs_path)) {
    message("Bypassing HMM parameterization for strictly structural Node-vs-Node analysis.")
    return(NULL)
  }

  hmm_class_path <- file.path(config$paths$intermediate_data, paste0("hmm_classification_", ref_species, "_ref_", comp_species, "_comp.rds"))

  if (file.exists(hmm_class_path)) {
    message("Info: Viterbi classifications already generated. Skipping.")
    return(hmm_class_path)
  }

  message(sprintf("\n--- Defining Transition & Emission Matrices (%s vs %s) ---", ref_species, comp_species))
  gene_obs <- readRDS(hmm_obs_path) |> dplyr::arrange(chromosome, start)

  # ----------------------------------------------------------------------------
  # 1. State Space Discovery
  # ----------------------------------------------------------------------------
  # Universally extract the true target ID regardless of comparison type.
  full_comp_chr_ids <- gene_obs |>
    dplyr::filter(stringr::str_detect(temp_observation, "^ON_")) |>
    dplyr::filter(!temp_observation %in% c("ON_MULTIPLE_B_CHRS", "ON_NO_ORTHOLOG")) |>
    dplyr::pull(temp_observation) |>
    stringr::str_replace_all("^ON_", "") |>
    unique() |> sort()

  if (length(full_comp_chr_ids) == 0) stop("CRITICAL ERROR: Zero specific spatial signals isolated.")

  # ----------------------------------------------------------------------------
  # 2. Matrix Assembly
  # ----------------------------------------------------------------------------
  hmm_states <- paste0("S_", full_comp_chr_ids)
  hmm_symbols_specific <- paste0("ON_", full_comp_chr_ids)
  all_symbols <- unique(c(hmm_symbols_specific, c("NON_SYN_OBS", "MULTIPLE_B_CHRS", "NO_ORTHOLOG"), unique(gene_obs$temp_observation)))
  all_symbols <- all_symbols[!is.na(all_symbols)]

  P_initial <- setNames(rep(1 / length(hmm_states), length(hmm_states)), hmm_states)

  # Transition Matrix
  P_trans <- matrix(0, nrow = length(hmm_states), ncol = length(hmm_states), dimnames = list(hmm_states, hmm_states))
  for (s in hmm_states) {
    P_trans[s, s] <- config$hmm$prob_self_syn_hmm1
    other_s <- setdiff(hmm_states, s)
    if (length(other_s) > 0) P_trans[s, other_s] <- config$hmm$prob_to_other_syn_hmm1 / length(other_s)
  }

  # Emission Matrix
  P_emis <- matrix(0, nrow = length(hmm_states), ncol = length(all_symbols), dimnames = list(hmm_states, all_symbols))
  explicit_sum <- config$hmm$prob_emit_correct_syn_hmm1_value + config$hmm$prob_emit_non_syn_obs_from_syn_hmm1_value +
    config$hmm$prob_emit_multiple_b_chrs_from_syn_hmm1_value + config$hmm$prob_emit_no_ortholog_from_syn_hmm1_value
  remaining_prob <- 1 - explicit_sum

  for (i in seq_along(full_comp_chr_ids)) {
    s_state <- hmm_states[i]
    s_sym <- hmm_symbols_specific[i]

    if (s_sym %in% all_symbols) P_emis[s_state, s_sym] <- config$hmm$prob_emit_correct_syn_hmm1_value
    if ("NON_SYN_OBS" %in% all_symbols) P_emis[s_state, "NON_SYN_OBS"] <- config$hmm$prob_emit_non_syn_obs_from_syn_hmm1_value
    if ("MULTIPLE_B_CHRS" %in% all_symbols) P_emis[s_state, "MULTIPLE_B_CHRS"] <- config$hmm$prob_emit_multiple_b_chrs_from_syn_hmm1_value
    if ("NO_ORTHOLOG" %in% all_symbols) P_emis[s_state, "NO_ORTHOLOG"] <- config$hmm$prob_emit_no_ortholog_from_syn_hmm1_value

    others <- setdiff(all_symbols, c(s_sym, "NON_SYN_OBS", "MULTIPLE_B_CHRS", "NO_ORTHOLOG"))
    if (length(others) > 0 && remaining_prob > 0) P_emis[s_state, others] <- remaining_prob / length(others)
  }

  # ----------------------------------------------------------------------------
  # 3. Pre-HMM Block Delineation & Fisher Filtering
  # ----------------------------------------------------------------------------
  message("\n--- Establishing Spatial Block Boundaries ---")

  clean_data <- gene_obs |>
    dplyr::filter(!is.na(chromosome) & chromosome != "") |>
    dplyr::select(gene_id, chromosome, start, end, inferred_state_hmm1 = temp_observation) |>
    dplyr::arrange(chromosome, start)

  # Pass config to classify_chromosome_blocks
  final_synteny_report <- split(clean_data, clean_data$chromosome) |>
    purrr::map_dfr(~classify_chromosome_blocks(.x, config)) |>
    dplyr::mutate(block_id = sprintf("%04d", dplyr::row_number()))

  block_data_for_join <- final_synteny_report |>
    dplyr::select(block_id, chromosome, block_start_pos = start_pos, block_end_pos = end_pos, inferred_state_blocks = inferred_state_final)

  gene_obs <- purrr::map2_dfr(
    .x = split(gene_obs, gene_obs$chromosome),
    .y = split(block_data_for_join, block_data_for_join$chromosome)[unique(gene_obs$chromosome)],
    .f = map_blocks_to_genes
  ) |>
    dplyr::mutate(fisher_key = paste(block_id, temp_observation, sep = "_"))

  message(sprintf("Evaluating spatial enrichment constraints (p < %s).", config$thresholds$fisher_p))

  fisher_results <- data.frame(ref_block_state = character(), comp_observation_symbol = character(), p_value = numeric(), odds_ratio = numeric())
  all_block_ids <- na.omit(unique(gene_obs$block_id))

  for (blk in all_block_ids) {
    for (sym in hmm_symbols_specific) {
      a <- sum(gene_obs$block_id == blk & gene_obs$temp_observation == sym, na.rm = TRUE)
      b <- sum(gene_obs$block_id == blk & gene_obs$temp_observation != sym, na.rm = TRUE)
      c <- sum(gene_obs$block_id != blk & gene_obs$temp_observation == sym, na.rm = TRUE)
      d <- sum(gene_obs$block_id != blk & gene_obs$temp_observation != sym, na.rm = TRUE)

      if (min(a,b,c,d) >= 0 && (a+b)>0 && (c+d)>0 && (a+c)>0 && (b+d)>0) {
        ft <- fisher.test(matrix(c(a, b, c, d), nrow = 2, byrow = TRUE), alternative = "greater")
        fisher_results <- rbind(fisher_results, data.frame(ref_block_state = blk, comp_observation_symbol = sym, p_value = ft$p.value, odds_ratio = ft$estimate))
      }
    }
  }

  fisher_results <- fisher_results |>
    dplyr::mutate(p_value_adjusted = p.adjust(p_value, method = "BH")) |>
    dplyr::filter(p_value_adjusted < config$thresholds$fisher_p & odds_ratio > config$thresholds$fisher_odds)

  enriched_keys <- paste(fisher_results$ref_block_state, fisher_results$comp_observation_symbol, sep = "_")

  gene_obs <- gene_obs |>
    dplyr::mutate(hmm1_obs = dplyr::case_when(
      temp_observation %in% c("NO_ORTHOLOG", "MULTIPLE_B_CHRS") ~ temp_observation,
      stringr::str_detect(temp_observation, "^ON_") & (fisher_key %in% enriched_keys) ~ temp_observation,
      TRUE ~ "NON_SYN_OBS"
    )) |>
    dplyr::select(-fisher_key, -inferred_state_blocks, -block_id)

  # ----------------------------------------------------------------------------
  # 4. Algorithmic Inference (Viterbi)
  # ----------------------------------------------------------------------------
  message("\n--- Decoding Hidden States via Viterbi Algorithm ---")

  hmm_model <- HMM::initHMM(States = hmm_states, Symbols = all_symbols, startProbs = P_initial, transProbs = P_trans, emissionProbs = P_emis)

  inferred_states_list <- purrr::map(split(gene_obs$hmm1_obs, gene_obs$chromosome), ~HMM::viterbi(hmm_model, .x))
  gene_obs$inferred_state_hmm1 <- unlist(inferred_states_list)

  # Contextual Reassignment
  gene_obs <- gene_obs |>
    dplyr::mutate(
      inferred_comp_chr = stringr::str_replace(inferred_state_hmm1, "^S_", ""),
      reassigned_temp_observation = dplyr::case_when(
        !is.na(inferred_comp_chr) & hmm1_obs %in% c("NON_SYN_OBS", "UNKNOWN_CLASSIFICATION") ~ "NON_SYN_OBS",
        temp_observation == "MULTIPLE_B_CHRS" & purrr::map2_lgl(all_comp_chromosomes, inferred_comp_chr, ~.y %in% .x) ~ paste0("ON_", inferred_comp_chr),
        temp_observation == "NO_ORTHOLOG" ~ "NO_ORTHOLOG",
        TRUE ~ temp_observation
      )
    ) |>
    dplyr::select(-inferred_comp_chr)

  saveRDS(gene_obs, hmm_class_path)
  message("Viterbi state resolution successfully cached.")

  return(hmm_class_path)
}
